WIP: 2019-07-03 11:28

diff --git a/App/Git/Scripts/git-validate b/App/Git/Scripts/git-validate
--- a/App/Git/Scripts/git-validate
+++ b/App/Git/Scripts/git-validate
@@ -11,8 +11,12 @@ CYAN='\033[0;36m'
 NC='\033[0m'
 declare -i ERROR_COUNTER=0
 
-if [ "$#" -eq 1 ]
-then
+COMMIT_FILES=$(git diff-tree --no-commit-id --name-only -r HEAD)
+if [[ "" != "${1}" ]]; then
+    COMMIT_FILES=$(git diff-tree --no-commit-id --name-only -r HEAD~${1})
+fi
+
+if [[ "$#" -eq 1 ]]; then
     oIFS=$IFS
     IFS=''
     SFILES="$1"
@@ -23,8 +27,7 @@ SFILES=${SFILES:-$STAGED_FILES_CMD}
 echo -e "$YELLOW ##### Checking staged files $NC"
 for FILE in $SFILES
 do
-    if [ -f $FILE ]
-    then
+    if [[ -f $FILE ]]; then
         ERROR=$(php -l $PROJECT/$FILE)
         rc=$?; if [[ $rc != 0 ]]; then echo -e "$RED$ERROR$NC"; fi
     fi
@@ -33,8 +36,17 @@ done
 echo -e "$CYAN ##### Checking modified files $NC"
 for FILE in $MODIFIED_FILES
 do
-    if [ -f $FILE ]
-    then
+    if [[ -f $FILE ]]; then
+        ERROR=$(php -l $PROJECT/$FILE)
+        rc=$?; if [[ $rc != 0 ]]; then echo -e "$RED$ERROR$NC"; fi
+    fi
+done
+
+echo -e "$CYAN ##### Checking last commit's modified files$NC"
+echo  $COMMIT_FILES
+for FILE in $COMMIT_FILES
+do
+    if [[ -f $FILE ]]; then
         ERROR=$(php -l $PROJECT/$FILE)
         rc=$?; if [[ $rc != 0 ]]; then echo -e "$RED$ERROR$NC"; fi
     fi
